### ISSUE TITLE
How to improve the displaying of the content?

### ISSUE THREAD

**Issue by orschiro** [LAJW/history-menu#1]
Dear @LAJW,

Thank you so much for your extension!

This is by far the best recent history search extension I could find. :-)

I have one question:

As you can see by the below screenshot, the content (e.g. headings) is not perfectly displayed and sometimes mismatched.

How can we improve the displaying of the content to perfectly match the theme?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17648397/ed0df142-6213-11e6-8b08-59687fcfadb5.png)

**Comment by LAJW** [comment]
Thanks for feedback!

I'm not sure, Please, expand.

Are you referring to the Window/Temporary? Tabs from closed windows are indented (create a window with multiple tabs, close it, open history menu and you'll see multiple items in there). By default closed windows are expanded, so you can easily browse contents of the window (settings can be changed in options panel).

And sometimes, when closing popups or last tab in a window, it may also show up as a window (which is a "feature" of Chrome itself).

**Comment by orschiro** [comment]
Dear @LAJW,

Let me try to be more precise then. 
1. `Recently Closed Tabs` is crossed out by a grey line. Maybe it should be displayed either above or below the line?
2. `3m` overlaps the tab name. Maybe this information could be displayed in front of the tab thumbnail?
3. Why do you differentiate between `Recently Closed Tabs` and `Recently Visited`? Why is this difference important when searching the history?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17651364/e5254834-6265-11e6-87a7-e5710bdc47bc.png)

**Comment by LAJW** [comment]
1. Good catch. Line should be behind title, and title should have white background.
2. The width of the popup is too small to display name, Behind those time markers, there are usually dots. Hovering mouse over an item should display full name and URL of the page. If that doesn't happen, then it's a bug, and I'm gonna fix it.
3. Closed tab is not a history entry. When restoring a tab, the back-button history is also restored (so-called session) and your current tab remains intact. Recently visited are just links (no session information) left-click to open in current tab, middle-click to open in new tab. When browsing the web, history is constantly updated with new links (even if no new tabs are being created or closed). Recently closed tabs are spawned only when a tab is closed. When you can't find a tab in recently closed, go to Recently Visited and it should be there. Also search is performed only on history.

I hope, that this answers your questions, and thanks for reporting those bugs (wouldn't notice them, as I'm not using Chrome these days). Will fix them first thing tomorrow morning.

**Comment by orschiro** [comment]
Thanks @LAJW!

> I hope, that this answers your questions, and thanks for reporting those bugs (wouldn't notice them, as I'm not using Chrome these days). Will fix them first thing tomorrow morning.

Looking forward to this update and I will report back how I receive the update. :+1: 

~Robert

**Comment by LAJW** [comment]
Fixed!
https://github.com/LAJW/history-menu/releases/tag/V2.0.2
Google Chrome Extension Store version should finish updating in couple hours.

**Comment by orschiro** [comment]
I just received the update and it looks much better now.

Thanks! :smile: 

![image](https://cloud.githubusercontent.com/assets/170947/17674021/fc2dfb16-6323-11e6-9135-dba3020c2c4d.png)

**Comment by LAJW** [comment]
Glad I could help, closing!
