### ISSUE TITLE
White flash before the popup appear in dark mode

### ISSUE THREAD

**Issue by oren64** [LAJW/history-menu#11]
When I press the extension button, the popup shows as a white blank for 1 millisecond before the content is shown in black mode.
I really love the extension, but this is really annoying.

Brave browser on Windows 10

**Comment by oren64** [comment]
Update: I changed the setting in chrome://flags/#enable-force-dark  to `Enabled with simple CIELAB-based inversion` and stopped using the Dark Reader extension.
And now I don't have this issue.

If you like, I can close this post.

**Comment by LAJW** [comment]
No, let's keep this open. It's possible we could make the background dark with embedded CSS or some other kind of hack.

**Comment by LAJW** [comment]
Flashbang fix is fixed and live on Chrome and Edge!
https://github.com/LAJW/history-menu/releases/tag/V2.5.0
