### ISSUE TITLE
Option "Expand closed windows" does not work

### ISSUE THREAD

**Issue by Dook1** [LAJW/history-menu#2]
Option "Expand closed windows" does not work

**Comment by Dook1** [comment]
#3

**Comment by LAJW** [comment]
https://github.com/LAJW/history-menu/releases/tag/V2.0.3
New version available through the web store:
https://chrome.google.com/webstore/detail/wrona-history-menu/fhibbdoaickjpmmhemkompghjjmpjdpj?hl=en-GB&authuser=0
