### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by Siegfriedmk** [LAJW/history-menu#9]
Hello. I'm interested to help you to translate the extension in Italian.
I already said it in the Chrome's page a few years ago, then I stopped to use Chrome :D

**Comment by LAJW** [comment]
Hi, thank you for your offer @Siegfriedmk!

You can simply download [this file](https://raw.githubusercontent.com/LAJW/history-menu/master/source/_locales/en/messages.json) and start translating it (the "description" field is only for translators - it only tells you where this message will go, so you don't have to translate that). You should be able to upload it here as an attachment. I'll turn on e-mail notifications to get a quicker response next time!

**Comment by Siegfriedmk** [comment]
Hello. Here it is.

[HistoryITA.txt](https://github.com/LAJW/history-menu/files/9443879/HistoryITA.txt)

I found nothing to adapt english time/date format to italian. For example, h=o (hours=ore)
I don't know if it's possible to edit that. If yes, considering are just a few letters, I can write here. 
As: english=italian
h=o, d=g, w=s, y=a
I didn't translate minutes and months, since the short is M also in italian

**Comment by LAJW** [comment]
I just included it in the [update 2.4.3](https://github.com/LAJW/history-menu/releases/tag/V2.4.3). Should be accepted to Google, Edge and Opera stores within a week.

**Comment by Siegfriedmk** [comment]
I saw it's on Chrome since a few days. Still nothing on Opera, where I got it

**Comment by LAJW** [comment]
It's been published on their dev channel.

```
Status has changed for Wrona History Menu
Wrona History Menu v2.4.4 on Opera Developer: Published.
Wrona History Menu v2.4.4 on Opera Next: Published.

Moderator's note:

Your extension needs to be manually reviewed and moderated before it can be added to Opera Stable. It is currently only viewable and available for download in Opera Developer and Opera Beta.

 Aug 29, 2022 11:49:17 PM UTC
 ```
 
I just realised however, they did not review the 2.4.2 version last year, and it's been stuck on 2.4.1 ever since without any feedback. Opera usually takes the longest to approve, but not that long.

**Comment by Siegfriedmk** [comment]
This is odd. I uninstalled Opera version of the extension, and I installed the Chrome version 2.4.3. Still no italian.

**Comment by LAJW** [comment]
Yeah, I made the mistake of calling the language "_ITA" rather than "_IT". An update is on the way (2.4.4, already deployed to Edge).

**Comment by LAJW** [comment]
Chrome version updated to 2.4.4. Should automatically switch to Italian.

**Comment by Siegfriedmk** [comment]
Yep, thanks, I saw it. Is it not possible to also change the "letter" for the time? For example, the H for hours, D for days, etc?

**Comment by LAJW** [comment]
It's certainly possible. I'll add it to the todo list (it'd probably be nice to translate it for all other languages).

**Comment by Siegfriedmk** [comment]
Ok, if you'll do it, and you'll need any help, I already translated it in the post where I linked the file.
Have a nice week

**Comment by LAJW** [comment]
Alright. Opera Add-ons are not responding - addon is only available in Opera preview. Please install Chrome version instead. Sorry for the inconvenience. It's up on Edge store as well.
